import Head from "next/head";
import Link from "next/link";
import { Layout } from "../../components";

export default function VerificationStatus({ status }) {
  console.log(status);
  return (
    <>
      <Head>
        <title>Verification Status</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Layout>
        <div className="flex flex-col items-center">
          <h1 className={"text-center text-xl " + (status === "verified" ? "text-blue-700" : "text-red-600")}>{status === "verified" ? "E-posta adresinizi doğruladığınız için teşekkürler..." : "Doğrulama sırasında hata oluştu. Lütfen site yöneticisiyle iletişime geçin. Teşekkürler..."}</h1>
          <Link href="/">
            <a className="text-white uppercase px-8 py-1 bg-blue-700 mt-4 text-sm cursor-pointer rounded-md font-semibold tracking-wider text-center">Anasayfa </a>
          </Link>
        </div>
      </Layout>
    </>
  );
}

VerificationStatus.getInitialProps = async ({ query }) => {
  const { status } = query;
  return { status };
};
